### ISSUE TITLE
cannot dynamically load position-independent executable

### ISSUE THREAD

**Issue by etam** [nixcloud/ip2unix#9]
I'm using openSUSE Tumbleweed (rolling release distro). It currently has gcc 9.3.1 and glibc 2.31.

I successfully built ip2unix version 2.1.1, but I get this error, when trying to use it:
```
ERROR: ld.so: object '/home/etam/tmp/ip2unix-2.1.1/build/ip2unix' from LD_PRELOAD cannot be preloaded (cannot dynamically load position-independent executable): ignored.
```

**Comment by aszlig** [comment]
The reason is that since glibc 2.30, it's [no longer possible to `dlopen`/LD_PRELOAD PIE objects](https://patchwork.ozlabs.org/patch/1055380/).

So to fix this, we need to split up the LD_PRELOAD library and the main executable.

**Comment by aszlig** [comment]
Fixed in 8e10ef2d1d76ba8835735eaab167e77de34df88a.

**Comment by etam** [comment]
Thanks for working on this, but it's still not working:

```
$ ./ip2unix -r in,path=/tmp/test.socket env
ERROR: ld.so: object './ip2unix' from LD_PRELOAD cannot be preloaded (cannot dynamically load executable): ignored.
...
LD_PRELOAD=./ip2unix
__IP2UNIX_RULES=i!!!!/tmp/test.socket&f!f!ff
```

**Comment by etam** [comment]
I think it's because `ldaddr` is in `ip2unix.cc`, which is compiled in the main executable, not in shared library (like in the example on StackOverflow you referenced in commit message).

**Comment by etam** [comment]
Another idea:
```
python3 ./scripts/gensyms.py ./src/preload.cc
{
  global: "__ip2unix__)(void"; [...]
  local: *;
};
```

**Comment by etam** [comment]
Got any idea why there are different addresses `0x4252e0 <__ip2unix__@plt>` and `0x7ffff7f5ad2f <__ip2unix__(int)>`?
```
$ gdb --args ./ip2unix -r in,path=/tmp/test.socket env
[...]
Reading symbols from ./ip2unix...
(gdb) b get_preload_libpath
Breakpoint 1 at 0x42b064: file ../src/ip2unix.cc, line 22.
(gdb) r
Starting program: /home/etam/tmp/ip2unix/build/ip2unix -r in,path=/tmp/test.socket env

Breakpoint 1, get_preload_libpath () at ../src/ip2unix.cc:22
22          if (dladdr(reinterpret_cast<void*>(__ip2unix__), &info) < 0) {
(gdb) n
27          return std::string(info.dli_fname);
(gdb) p info
$1 = {
    dli_fname = 0x7fffffffdf97 "/home/etam/tmp/ip2unix/build/ip2unix",
    dli_fbase = 0x400000,
    dli_sname = 0x418878 "__ip2unix__",
    dli_saddr = 0x4252e0 <__ip2unix__@plt>
}
(gdb) p __ip2unix__
$2 = {const char *(int)} 0x7ffff7f5ad2f <__ip2unix__(int)>
```

**Comment by etam** [comment]
I got it!
Here's the problem: https://stackoverflow.com/questions/5469274/what-does-plt-mean-here
Here's the solution: use `meson -Db_pie=true build`
